/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JsonObjectParser;

import io.vertx.core.Vertx;
import io.vertx.core.DeploymentOptions;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

				Vertx vertx = Vertx.vertx();

				vertx.deployVerticle(TCPServerVerticle.class, new DeploymentOptions());
    }
}
